.PHONY: test

all:
	@echo "Alles klar."

test:
	./test_verbindung.sh

clean:
	rm node01/.ssh/id_ed25519*
	rm node01/.ssh/authorized_keys
	rm node02/.ssh/id_ed25519*
	rm node02/.ssh/authorized_keys
	rm node03/.ssh/id_ed25519*
	rm node03/.ssh/authorized_keys
